name: 'My Node.js Action'
description: 'Uma action para executar um script Node.js'

inputs:
  vars:
    description: 'Variáveis de ambiente'
    required: false
    default: '{
      "var1": "value1",
      "var2": "value2"
      }'
  node_version:
    description: 'Versão do Node.js a ser usada'
    required: false
    default: '20.11.1'

runs:
  using: 'composite'
  steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}

    - name: Instalar dependências
      run: |
        npm install
      shell: bash

    - name: Executar script Node.js
      run: |
        node ./index.js --vars='${{ inputs.vars }}'
        ls -la
        cat vars.txt
        echo "ECHO HOSTS=$(cat vars.txt)"
        echo "HOSTS=$(cat vars.txt)" >> $GITHUB_OUTPUT
      shell: bash
