name: 'My Node.js Action'
description: 'Uma action para executar um script Node.js'

inputs:
  vars:
    description: 'Variáveis de ambiente'
    required: 
    default: '{}'
  node_version:
    description: 'Versão do Node.js a ser usada'
    required: false
    default: '20'

runs:
  using: 'composite'
  steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}

    - name: Instalar dependências
      run: |
        npm install
      shell: bash

    - name: Executar script Node.js
      run: |
        node ./index.js
      shell: bash
