name: Deploy to hosts
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        exclude:
          - host: ${{ vars.HOST_1 }}
        host:
          - ${{ vars.HOST_1 }}
          - ${{ vars.HOST_2 }}
          - ${{ vars.HOST_3 }}
          - ${{ vars.HOST_4 }}
          - ${{ vars.HOST_5 }}
          - ${{ vars.HOST_6 }}
          - ${{ vars.HOST_7 }}
          - ${{ vars.HOST_8 }}
          - ${{ vars.HOST_9 }}
          - ${{ vars.HOST_10 }}
          - ${{ vars.HOST_11 }}
          - ${{ vars.HOST_12 }}
          - ${{ vars.HOST_13 }}
          - ${{ vars.HOST_14 }}
          - ${{ vars.HOST_15 }}

    steps:
      - name: Deploy to hosts
        run: |
          echo "Deploying to host: ${{ matrix.host }}"
