name: Deploy to hosts

on:
  push:
    branches:
      - main

jobs:
  generate-vars:
    runs-on: ubuntu-latest
    outputs:
      hosts: ${{ steps.generate-vars.outputs.hosts }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Usar minha ação personalizada
        uses: ./.github/actions/test-node-action
        with:
          vars: ${{ toJson(vars) }}
          
      - name: Generate IP Array
        id: generate-vars
        run: |
          HOSTS=$(cat vars.txt)
          echo "HOSTS=$HOSTS" >> $GITHUB_OUTPUT

  deploy:
    needs: generate-vars
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host: ${{ fromJson(needs.generate-vars.outputs.hosts) }}
    steps:
      - name: Deploy to hosts
        if: ${{ matrix.host }}
        run: |
          echo "Deploying to host: ${{ matrix.host }}"
 