name: Deploy to hosts
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host:
          - ${{ github.event.ref == 'refs/heads/staging' && vars.HOST_1 }}
          - ${{ github.event.ref == 'refs/heads/staging' && vars.HOST_2 }}
          - ${{ github.event.ref == 'refs/heads/main' && vars.HOST_3 }}
          - ${{ github.event.ref == 'refs/heads/main' && vars.HOST_4 }}
          - ${{ github.event.ref == 'refs/heads/main' && vars.HOST_5 }}
          - ${{ github.event.ref == 'refs/heads/main' && vars.HOST_6 }}
          - ${{ github.event.ref == 'refs/heads/main' && vars.HOST_7 }}
          - ${{ github.event.ref == 'refs/heads/main' && vars.HOST_8 }}
          - ${{ github.event.ref == 'refs/heads/main' && vars.HOST_9 }}
          - ${{ github.event.ref == 'refs/heads/main' && vars.HOST_10 }}
          - ${{ github.event.ref == 'refs/heads/main' && vars.HOST_11 }}
          - ${{ github.event.ref == 'refs/heads/main' && vars.HOST_12 }}
          - ${{ github.event.ref == 'refs/heads/main' && vars.HOST_13 }}
          - ${{ github.event.ref == 'refs/heads/main' && vars.HOST_14 }}
          - ${{ github.event.ref == 'refs/heads/main' && vars.HOST_15 }}
            
    steps:
      - name: Deploy to hosts
        if: ${{ matrix.host }}
        run: |
          echo "Deploying to host: ${{ matrix.host }}"
