name: Deploy to hosts
on:
  push:

env:
  ALL_HOSTS: |
    "${{ vars.HOST_1 }}", "${{ vars.HOST_2 }}", "${{ vars.HOST_3 }}"
jobs:
  define-hosts:
    runs-on: ubuntu-latest
    outputs:
      hosts: ${{ steps.define-hosts.outputs.hosts }}

    steps:
      - name: Define hosts
        id: define-hosts
        run: |
          echo 'hosts=[${{ env.ALL_HOSTS }}]'
          echo 'hosts=[${{ env.ALL_HOSTS }}]' >> $GITHUB_OUTPUT
  deploy:
    runs-on: ubuntu-latest
    needs: define-hosts
    strategy:
      matrix:
        host: ${{ fromJson(needs.define-hosts.outputs.hosts) }}
    steps:
      - name: Deploy to hosts
        run: |
          echo "Deploying to hosts... matrix: ${{ matrix.host }}"
