name: Deploy to hosts
on:
  push:


jobs:
  define-hosts:
    runs-on: ubuntu-latest
    steps:
      - name: Define hosts
        run: |
          hosts=["${{ vars.HOST_1 }}", "${{ vars.HOST_2 }}", "${{ vars.HOST_3 }}"]
          echo "hosts=$hosts" >> $GITHUB_OUTPUT
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host: ${{ fromJson(needs.define-hosts.outputs.hosts) }}
    steps:
      - name: Deploy to hosts
        run: |
          echo "Deploying to hosts... matrix: ${{ matrix.host }}"
