name: Deploy to hosts
on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host:
          - ${{ vars.HOST_1 }}
          - ${{ vars.HOST_2 }}
          - ${{ vars.HOST_3 }}
          - ${{ vars.HOST_4 }}
          - ${{ vars.HOST_5 }}
    steps:
      - name: Deploy to hosts
        run: |
          echo "Deploying to hosts... matrix: ${{ matrix.host }}"