name: Deploy to hosts
on:
  push:

jobs:
  define-hosts:
    runs-on: ubuntu-latest
    outputs:
      hosts: ${{ steps.define-hosts.outputs.hosts }}

    steps:
      - name: Define hosts
        id: define-hosts
        run: |
          ALL_HOSTS=(
            ${{ vars.HOST_1 }}
            ${{ vars.HOST_2 }}
            ${{ vars.HOST_3 }}
            ${{ vars.HOST_4 }}
            ${{ vars.HOST_5 }}
            ${{ vars.HOST_6 }}
            ${{ vars.HOST_7 }}
            ${{ vars.HOST_8 }}
            ${{ vars.HOST_9 }}
            ${{ vars.HOST_10 }}
            ${{ vars.HOST_11 }}
            ${{ vars.HOST_12 }}
            ${{ vars.HOST_13 }}
            ${{ vars.HOST_14 }}
            ${{ vars.HOST_15 }}
          )

          # Obter a mensagem do commit
          commit_message=${{ github.event.head_commit.message }}
          echo "Commit message: $commit_message"

          # Verificar se o commit contém '--hosts=[]'
          if echo "$commit_message" | grep -q -- '--hosts=\['; then
            # Extrair valores do array --hosts=[]
            host_list=$(echo "$commit_message" | grep -oP '(?<=--hosts=\[).+?(?=\])')
            echo "Hosts no commit: $host_list"
          else
            # Nenhum filtro, incluir todos os hosts
            host_list=""
          fi

          # Criar um array JSON válido
          json_hosts="["
          for host in "${ALL_HOSTS[@]}"; do
            if [ -n "$host" ]; then
              # Se houver filtro, incluir apenas se o host estiver na lista
              if [ -z "$host_list" ] || echo ",$host_list," | grep -q ",$host,"; then
                json_hosts+="\"$host\","
              fi
            fi
          done
          json_hosts="${json_hosts%,}]" # Remover a última vírgula e fechar o array

          echo "hosts=$json_hosts" >> $GITHUB_OUTPUT
          echo "JSON hosts: $json_hosts"

  deploy:
    runs-on: ubuntu-latest
    needs: define-hosts
    strategy:
      matrix:
        host: ${{ fromJson(needs.define-hosts.outputs.hosts) }}

    steps:
      - name: Deploy to hosts
        run: |
          echo "Deploying to host: ${{ matrix.host }}"
