name: Deploy to hosts
on:
  push:
jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      vars: ${{ steps.vars.outputs.HOSTS }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Usar minha ação personalizada
        uses: ./.github/actions/test-node-action
        with:
          vars: ${{ toJson(vars) }}
        id: vars
  log:
    runs-on: ubuntu-latest
    needs: vars
    steps:
      - name: Log vars
        run: echo "LOGS ${{ needs.vars.outputs.vars }}"

  deploy:
    needs: vars
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host: ${{ fromJson(needs.vars.outputs.vars) }}
    steps:
      - name: Deploy to hosts
        if: ${{ matrix.host }}
        run: |
          echo "Deploying to host: ${{ matrix.host }}"
