name: Deploy to hosts
on:
  push:
jobs:
  generate-vars:
    runs-on: ubuntu-latest
    outputs:
      hosts: ${{ steps.generate-vars.outputs.HOSTS }}
      test: ${{ steps.generate-vars.outputs.TEST }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Usar minha ação personalizada
        uses: ./.github/actions/test-node-action
        with:
          vars: ${{ toJson(vars) }}
        id: generate-vars
      - run: |
          echo "TEST: ${{ steps.generate-vars.outputs.TEST }}"
          echo "test: ${{ steps.generate-vars.outputs.test }}"
          echo "HOST: ${{ steps.generate-vars.outputs.HOST }}"
          echo "Hosts: ${{ steps.generate-vars.outputs.hosts }}"
  log:
    runs-on: ubuntu-latest
    needs: generate-vars
    steps:
      - name: Log vars
        run: echo "LOGS ${{ needs.generate-vars.outputs.hosts }}"

  # deploy:
  #   needs: generate-vars
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       host: ${{ fromJson(needs.vars.outputs.hosts) }}
  #   steps:
  #     - name: Deploy to hosts
  #       if: ${{ matrix.host }}
  #       run: |
  #         echo "Deploying to host: ${{ matrix.host }}"
 