name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  generate-hosts:
    runs-on: ubuntu-latest
    outputs:
      hosts: ${{ steps.custom-action.outputs.HOSTS }}
    steps:
      - name: Usar a ação reutilizável
        uses: ./.github/actions/test-node-action
        with:
          vars: ${{ toJson(vars) }}
          node_version: '20.11.1'
        id: custom-action

  deploy:
    needs: generate-hosts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host: ${{ fromJson(needs.generate-hosts.outputs.hosts) }}
    steps:
      - name: Deploy to host
        run: |
          echo "Deploying to ${{ matrix.host }}"
