name: Deploy to hosts
on:
  push:

jobs:
  define-hosts:
    runs-on: ubuntu-latest
    outputs:
      hosts: ${{ steps.define-hosts.outputs.hosts }}

    steps:
      - name: Define hosts
        id: define-hosts
        run: |
          ALL_HOSTS=(
            ${{ vars.HOST_2 }}
            ${{ vars.HOST_1 }}
            ${{ vars.HOST_3 }}
            ${{ vars.HOST_4 }}
            ${{ vars.HOST_5 }}
            ${{ vars.HOST_6 }}
            ${{ vars.HOST_7 }}
            ${{ vars.HOST_8 }}
            ${{ vars.HOST_9 }}
            ${{ vars.HOST_10 }}
            ${{ vars.HOST_11 }}
            ${{ vars.HOST_12 }}
            ${{ vars.HOST_13 }}
            ${{ vars.HOST_14 }}
            ${{ vars.HOST_15 }}
          )
          hosts=""
          for host in ${ALL_HOSTS[@]}; do
            echo $host
            hosts+="\"$host\","
          done
          echo $hosts
          echo 'hosts=$hosts' >> $GITHUB_OUTPUT
  deploy:
    runs-on: ubuntu-latest
    needs: define-hosts
    strategy:
      matrix:
        host: ${{ fromJson(needs.define-hosts.outputs.hosts) }}
    steps:
      - name: Deploy to hosts
        run: |
          echo "Deploying to hosts... matrix: ${{ matrix.host }}"
