name: Generate and Use IP Array

on:
  push:
    branches:
      - main2

jobs:
  generate-ips:
    runs-on: ubuntu-latest
    outputs:
      ip-list: ${{ steps.set-output.outputs.ip-list }}
    steps:
      - name: Generate IP Array
        id: set-output
        run: |
          # Gera um array de IPs fictícios
          IPS='["192.168.1.1", "192.168.1.2", "192.168.1.3"]'
          echo "IPS=$IPS"
          # Define o output com o array
          echo "::set-output name=ip-list::$IPS"

  use-ips:
    needs: generate-ips
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ip: ${{ fromJson(needs.generate-ips.outputs.ip-list) }}
    steps:
      - name: Process IP
        run: |
          echo "Processing IP: ${{ matrix.ip }}"
