name: List Vars Context

on:
  push:
    branches:
      - main

jobs:
  list-vars:
    runs-on: ubuntu-latest
    steps:
      - name: List all vars
        uses: easyware-io/export-to-env@v1
        with:
          vars: ${{ toJSON(vars) }}
      - run: |
          # Criar um array vazio
            declare -a env_array

            # Preencher o array com todas as variáveis de ambiente
            while IFS='=' read -r name value; do
              env_array+=("$name=$value")
            done < <(env)

            # Exibir todas as variáveis de ambiente armazenadas no array
            for var in "${env_array[@]}"; do
              echo "$var"
            done