name: List Vars Context

on:
  push:
    branches:
      - main

jobs:
  list-vars:
    runs-on: ubuntu-latest
    steps:
      - name: List all vars
        uses: easyware-io/export-to-env@v1
        with:
          vars: ${{ toJSON(vars) }}
      - run: |
          # Prefixo para filtrar
          prefix="HOST_"

          # Criar um array vazio
          declare -a filtered_env_array

          # Filtrar as variáveis de ambiente que começam com o prefixo
          while IFS='=' read -r name value; do
            if [[ "$name" == $prefix* ]]; then
              filtered_env_array+=("$name=$value")
            fi
          done < <(env)

          # Exibir as variáveis de ambiente filtradas
          for var in "${filtered_env_array[@]}"; do
            echo "$var"
          done