name: Call a reusable workflow and use its outputs

on:
  push: 

jobs:
  job1:
    uses: brsantos197/github-actions/.github/actions/test-node-action/action.yml@main

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
